# Generated by Django 4.1.4 on 2023-01-10 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_remove_userprofile_uniquecode'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='uniqueCode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
