# Generated by Django 4.1.4 on 2023-01-19 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_reset'),
    ]

    operations = [
        migrations.DeleteModel(
            name='reset',
        ),
        migrations.RemoveField(
            model_name='employerprofile',
            name='company_email',
        ),
        migrations.RemoveField(
            model_name='employerprofile',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='company',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_recruiter',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='uniqueCode',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_recruiter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='company',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='uniqueCode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
