# Generated by Django 4.1.4 on 2023-01-19 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_delete_reset_remove_employerprofile_company_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerprofile',
            name='is_recruiter',
            field=models.BooleanField(default=False),
        ),
    ]
