# Generated by Django 4.1.4 on 2022-12-22 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_candidatesapplied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='experience',
            field=models.CharField(choices=[('No Expirence', 'No Expirience'), ('1-Year', 'One Year'), ('2-years', 'Two Year'), ('3-Year&above', 'Three Year Plus')], default='No Expirence', max_length=20),
        ),
    ]
