# Generated by Django 4.1.4 on 2023-02-07 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_candidatesapplied_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatesapplied',
            name='status',
            field=models.CharField(blank=True, default='Pending', max_length=255, null=True),
        ),
    ]
